
# Additional flags to pass to the Objective-C compiler
ADDITIONAL_OBJCFLAGS += -Wall

# Additional flags to pass to the C compiler
ADDITIONAL_CFLAGS += -Wall

ADDITIONAL_INCLUDE_DIRS += `pkg-config --cflags libgphoto2`

Snapshot_GUI_LIBS += -lCameraKitSchik 

ifneq ($(freedesktop), no)
  Snapshot_GUI_LIBS += -lFreeDesktopKit
endif

Snapshot_GUI_LIBS += `pkg-config --libs libgphoto2`

